#shark's mostly stolen mangowm conffig

#monitor config, change as needed
monitorrule=name:Virtual-1,width:2048,height:1152,refresh:60,x:0,y:0

#cursor
cursor_theme=Bibata-Modern-Ice
cursor_size=24

#color scheme
rootcolor=0x000000ff
bordercolor=0xfffcffff
focuscolor=0xffabfcff
urgentcolor=0x888888ff
#border
borderpx=3
gappih=5
gappiv=5
gappoh=10
gappov=10

#tiling type fair
tagrule=id:1,monitor_name:Virtual-1,layout_name:fair

#anims
animations=1
layer_animations=1
animation_type_open=slide
animation_type_close=slide
layer_animation_type_open=slide
layer_animation_type_close=slide

#startup
exec-once=/usr/lib/xdg-desktop-portal-wlr &
exec-once=wl-clip-persist -clipboard regular --reconnect-tries 0 &
exec-once=wl-paste --type text --watch cliphist store &
exec-once=swaybg -i /home/shark/walls/felix.jpg -m fill &
exec-once=waybar

#keyboard
repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=us,de
xkb_rules_options=grp:alt_caps_toggle

#binds
#core
bind=SUPER,R,spawn,kitty
bind=SUPER,d,spawn,librewolf
bind=SUPER,w,killclient

#focusing
bind=SUPER,Tab,focusstack,next
bind=ALT,Left,focusdir,left
bind=ALT,Right,focusdir,right
bind=ALT,Up,focusdir,up
bind=ALT,Down,focusdir,down

#swapping
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

#floating
bind=SUPER+SHIFT,f,togglefloating

#tag switch
bind=SUPER,Left,viewtoleft,0
bind=SUPER,Right,viewtoright,0
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0

#view tags
bind=Ctrl,1,view,1,0
bind=Ctrl,2,view,2,0
bind=Ctrl,3,view,3,0
bind=Ctrl,4,view,4,0
bind=Ctrl,5,view,5,0
bind=Ctrl,6,view,6,0
bind=Ctrl,7,view,7,0
bind=Ctrl,8,view,8,0
bind=Ctrl,9,view,9,0

#screenshot
bind=NONE,Print,spawn_shell,g=$(slurp -d) && [ -n "$g" ] && grim -g "$g" $HOME/Pictures/Screenshots/$(date +%d%H%M%S).png

#audio
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=SHIFT,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

#resize
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize

#etc keybinds, DONT REMOVE!!!
bind=SUPER+SHIFT,R,reload_config
bind=SUPER+SHIFT,M,quit


