CPU_SCALING_GOVERNER_ON_AC=performance
CPU_SCALING_GOVERNER_ON_BAT=powersave

CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0

CPU_HWP_DYN_BOOST_ON_AC=1
CPU_HWP_DYN_BOOST_ON_BAT=0

ENERGY_PREF_POLICY_ON_AC=balance_performance
ENERGY_PREF_POLICY_ON_BAT=power

CPU_MAX_PERF_ON_AC=100
CPU_MAX_PERF_ON_BAT=30

CPU_BOOST_HWP_ON_AC=40
CPU_BOOST_HWP_ON_BAT=1

RADEON_DPM_PERF_LEVEL_ON_AC=auto
RADEON_DPM_PERF_LEVEL_ON_BAT=low
RADEON_DPM_STATE_ON_AC=performance
RADEON_DPM_STATE_ON_BAT=battery

DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE="bluetooth wwan"

ENABLE_LAPTOP_MODE_ON_AC=0
ENABLE_LAPTOP_MODE_ON_BAT=1

MAX_LOST_WORK_SECS_ON_BAT=120
MAX_LOST_WORK_SECS_ON_AC=15

VM_WRITEBACK_ON_BAT=1
VM_DIRTY_RATIO_ON_BAT=40

SCHED_POWERSAVE_ON_AC=0
SCHED_POWERSAVE_ON_BAT=1

PLATFORM_PROFILE_ON_AC=balanced
PLATFORM_PROFILE_ON_BAT=low-power

RUNTIME_PM_ON_BAT=auto
RUNTIME_PM_ALL=1

USB_AUTOSUSPEND=1
USB_AUTOSUSPEND_DISABLE_ON_SHUTDOWN=1

SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=1
SOUND_POWER_SAVE_CONTROLLER=Y

WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=on

PCIE_ASPM_ON_BAT=powersupersave

DISK_DEVICES="nvme0n1"
DISK_IOSCHED="mq-deadline"
DISK_SPINDOWN_TIMEOUT_ON_BAT="0"


MEM_SLEEP_ON_AC=s2idle
MEM_SLEEP_ON_BAT=s2idle

DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE="bluetooth wwan wifi"

DEVICES_TO_DISABLE_ON_STARTUP="bluetooth wwan"

RESTORE_DEVICE_STATE_ON_STARTUP=1

